name: App Store Review Trigger

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: feature/appstore
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Create playstore.config.json from environment
        run: echo '${{ secrets.PLAYSTORE_CONFIG_JSON }}' > playstore.config.json
        env:
          PLAYSTORE_CONFIG_JSON: ${{ secrets.PLAYSTORE_CONFIG_JSON }}

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run AppStore review checker
        run: npm run prod

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add feature/appStore/storage.json
          git commit -m ":card_file_box: Update processed playstore reviews storage" || exit 0
          git push
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
